const types = {
  ADD_TODO: 'todo/add',
  DELETE_TODO: 'todo/delete',
  TOGGLE_TODO: 'todo/toggle',

  GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

  ADD_TODOS_REQUEST: 'ADD_TODOS_REQUEST',
  ADD_TODOS_SUCCESS: 'ADD_TODOS_SUCCESS',
  ADD_TODOS_FAILURE: 'ADD_TODOS_FAILURE',

  DELETE_TODOS_REQUEST: 'DELETE_TODOS_REQUEST',
  DELETE_TODOS_SUCCESS: 'DELETE_TODOS_SUCCESS',
  DELETE_TODOS_FAILURE: 'DELETE_TODOS_FAILURE',

  TOGGLE_TODOS_REQUEST: 'TOGGLE_TODOS_REQUEST',
  TOGGLE_TODOS_SUCCESS: 'TOGGLE_TODOS_SUCCESS',
  TOGGLE_TODOS_FAILURE: 'TOGGLE_TODOS_FAILURE',
};

export default types;
